% train_glimpse_model( MODEL_NAME, POS_DIR, NEG_DIR, [NUM_PROTOTYPES] )

model_names = {...
    'dogs', ...
    'pedestrians', ...
    'leashes' };

pos_dirs = {...
    '/u/quinn/mm-group/mm-group-images/training-sets/dogs', ...
    '/u/quinn/mm-group/mm-group-images/training-sets/humans', ...
    '/u/quinn/mm-group/mm-group-images/training-sets/leashes' };

neg_dirs = {...
    '/u/quinn/mm-group/mm-group-images/training-sets/dist_dogs', ...
    '/u/quinn/mm-group/mm-group-images/training-sets/dist_humans', ...
    '/u/quinn/mm-group/mm-group-images/training-sets/dist_leashes' };

for i = 1:length(model_names)
   
    tic;
    train_glimpse_model(model_names{i}, pos_dirs{i}, neg_dirs{i} )
    fprintf('%s model constructed %.3f\n',model_names{i}, toc);
    
end


